### ISSUE TITLE
Compiling the Python

### ISSUE THREAD

**Issue by kaleguy** [rossw01/Flashcard#17]
Great project!

Trying to build the Python script. Had some issues but looks like it was my antivirus software. Tried to delete this but doesn't seem like I can. Still looking into it.

**Comment by kaleguy** [comment]
New to Python, asked ChatGPT and it told me to run PyInstaller --onefile parseAnki.py, did so and got errors, looking into it.

**Comment by rossw01** [comment]
> Had some issues but looks like it was my antivirus software.

Sorry for the late reply, did you manage to get it working in the end? Let me know if there's anything I can help with, otherwise I can close the issue 🙂.
